//TODO
const GENERAL = {fname: "Heeyun", lname: "Kim"};
const THEME = {follower: "airplane.png", aniImage:"pixelCloudBack.png", bullet:"umbrella.png", menuImg:"menuCloud.png", clickedMenuImg:"rainbowCloud.png", menuClickedEffect: "longRain.gif"}
const PORTFOLIO = [{menuTitle:"About me",subTitle:"Who Am I", contents:[{boxTitle:"Heeyun Kim", boxContents:"Enthusiastic student majoring in software engineering. Passionate in cybersecurity and data science.", boxPicture:"HeeyunProfile.png"},{boxTitle:"Skills", boxContents: "<b>- Computer Skills:</b> <ul> <li>Java</li> <li>Python</li> <li>HTML, CSS, JavaScript</li> <li>Linux system</li> <li>SQL</li> <li>Microsoft Office skills</li></ul>", boxPicture:"cloud1.png"},{boxTitle:"Language", boxContents:"<ol> <li>Proficient Korean</li> <li>English</li> <ol>", boxPicture:null}]},
{menuTitle:"Academics",  subTitle:"What & Where I Learned", contents:[
    {boxTitle:"Brooklyn Technical High School", boxContents:"<i>2017-2021</i> <br /> Software Engineering Major <br /> <br /> Click the school icon below to see the portfolio page about my high school life: <br /> <br /><a href = 'highschool.html'><img class = 'hypPic'src = 'images/school_pixel.png'/></a>", boxPicture:"bths.jpg"},
    {boxTitle:"Columbia Univerisity", boxContents: "<i>2021-present</i> <br /><br /> <b>School: </b>Fu Foundation School of Engineering and Applied Science <br /><br /> <b>Intended Major: </b> Computer Science", boxPicture:"columbia.png"}]},
{menuTitle:"Work Experience", subTitle:"What I Did", contents:[
    {boxTitle:"Connected Computing & Media Processing AI Research Lab", boxContents:"2020, in Kyungpook National University of Korea <br /><br /> Investigated how Deep Q-learning AI can be implemented in Green City traffic light systems.", boxPicture:"CCMP.jpeg"},
    {boxTitle:"Responsible Data Science Lab", boxContents: "2019 in NYU, NY <i> through ARISE (Applied Research Innovations in Science and Engineering) Program</i> <br /><br /> Assisted in data analysis using Python. <br /> Mined and organized Big Data to validate the lab-developed algorithm to forecast the public's candidate preference during voting. <br /><br /> <a href='https://engineering.nyu.edu/arise-2019-colloquium'>ARISE 2019 website</a> <br /><br /> <a href = 'datafiles/HKim,KGumbs.pdf'>See research poster</a>", boxPicture:"ResponsibleData.jpg", hidden_title: "Abstract", hidden: "    Computational social choice is an interdisciplinary area of research and practice that combines insights from mathematics, logic, economics and computer science to aggregate preferences of individuals to arrive at a society-wide consensus. In a standard election, selecting a winner is trivial: simply pick the candidate with the majority of votes. However, as the number of candidates increases and different voting rules are used, it becomes increasingly difficult to determine the outcome. More specifically, dealing with incompleteness and uncertainty, an inherent characteristic of polling is a serious challenge confronted in this field of research. While initial computational social choice researchers focused on formulating algorithms to determine winners given partial preferences, currently work is being done to carry this forward to implement and optimize such algorithms. Despite the importance of the problem, there is no comprehensive, public dataset of partial preferences of real-world elections. To address this, we mine datasets of recommender systems and rating websites to develop a comprehensive dataset of partial preferences, where each voter (e.g., viewers on Netflix) gives their preferences over a subset of candidates (e.g., movies on Netflix). We plan to use this dataset to validate our optimizations of the algorithms we are developing, and to eventually make this dataset public."}]},
{menuTitle:"Projects", subTitle:"What I made", contents:[
    {boxTitle:"Be My Guest <i> - Java </i>", boxContents:"Walk around the lounge. Get some drink, talk to people, and play mini games! <br /> <br /> Reminiscing Nintendo Pokemon games in my childhood, I designed this project base on old Pokemon games. <br /><br /> <a href = 'https://github.com/heeyunki-mp3/Be_My_Guest'>Github page</a> of this project", boxPicture:"BeMyGuest.gif"},
    {boxTitle:"Updating other projects... ", boxContents:"Pokemon Type Internet Game, Voltorb Flip Game, and more projects will be up here soon!", boxPicture:null}]},
{menuTitle:"Contacts",  subTitle:"Where I Can Be Reached", contents:[{boxTitle:"Email", boxContents:"hk3187@columbia.edu", boxPicture:null},{boxTitle:"Social Media", boxContents: "<b>Instagram: </b> @heeyun_kim <br /> <br /> <b>Facebook: </b> Heeyun Kim", boxPicture:null}]}];